version: 0.2
phases:
  install:
    commands:
      - echo "Creating Python virtual environment and installing dependencies..."
      - python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Activating virtual environment..."
      - . venv/bin/activate
  build:
    commands:
      - echo "Activating virtual environment and building the MkDocs site..."
      - . venv/bin/activate
      - mkdocs build --clean
  post_build:
    commands:
      - echo "Copying appspec.yml into the build artifact directory..."
      - cp appspec.yml site/appspec.yml
artifacts:
  files:
    - '**/*'
  base-directory: site
