site_name: FND docs
site_url: https://docs-fnd.betv3.xyz
theme: 
  name: material
nav:
  - Home: index.md
  - Abstract:
    - FND GUI:
      - Admin: views/Admin.md
      - Apps: views/Apps.md
      - Config: views/Config.md
      - Dashboard: views/Dashboard.md
      - Device Details: views/Device Details.md
      - Devices: views/Devices.md
    - Overview: Overview.md
  - Properties:
    - Device Properties: properties/air_pollution_meter_properties.md
  - Registration: 
    - Overview: registration/index.md
    - CLI Workflow: registration/cli-workflow.md
    - Data Flow: registration/data-flow.md
    - Add Device: registration/add-device.md
    - Register Device: registration/register-device.md
extra:
  css_files:
    - css/extra.css
